### ISSUE TITLE
Unable to debug JS in chain mode (safari)

### ISSUE THREAD

**Issue by Roseinfire** [vsnits/HtmlS#6]
# Description
`import chain "source.js"` is htmls command which fetch JS files with `syncFetch` (read documentation) <br>
  and puts responses one after another in the `<script>` tags.
# Location
  When the fetched script gives an error, web inspector navigates to htmls code, but not fetched JavaScript.
# Browser
  * Safari .latest (macos big sur)
<br>

**Comment by vsnits** [comment]
Maybe use `blob` urls to apply new scripts. Separation + blobs should be enough.

**Comment by vsnits** [comment]
All n all the project is closed.
